### ISSUE TITLE
Appendix F setting

### ISSUE THREAD

**Issue by dlguswn3659** [pym1024/SWAP#1]
Hello,

I ran the previous version of the code that contains ```search.py```.

The code has the following default settings:

```
args = Namespace(cycles=50, data_path='datasets', dataset_name='cifar10', device='cuda', history_path='histories', init_channels=3, input_batch=16, input_dim=32, layers=1, log_path='logs', mutation_times=68, num_classes=10, population_size=128, repeats=32, sample_size=64, search_space='DARTS', seed=0)
```

> args = Namespace(cycles=50, data_path='datasets', dataset_name='cifar10', device='cuda', history_path='histories', init_channels=3, input_batch=16, input_dim=32, layers=1, log_path='logs', mutation_times=68, num_classes=10, population_size=128, repeats=32, sample_size=64, search_space='DARTS', seed=0)

```
# DARTS search space
OPERATIONS = ['input', 'max_pool_3x3', 'avg_pool_3x3', 'skip_connect', 'sep_conv_3x3', 'sep_conv_5x5', 'dil_conv_3x3', 'dil_conv_5x5', 'output']
```

> OPERATIONS = ['input', 'max_pool_3x3', 'avg_pool_3x3', 'skip_connect', 'sep_conv_3x3', 'sep_conv_5x5', 'dil_conv_3x3', 'dil_conv_5x5', 'output']

When running the code with default settings, as the evolution progresses, it seems that only architectures composed solely of 'sep_conv_3x3' and 'sep_conv_5x5' operations are considered for computation.

> INFO  Best architecture: [Genotype(normal=[('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 2), ('sep_conv_3x3', 2), ('sep_conv_3x3', 3), ('sep_conv_5x5', 3), ('sep_conv_3x3', 4), ('sep_conv_3x3', 3)], normal_concat=[2, 3, 4, 5], reduce=[('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 2), ('sep_conv_3x3', 2), ('sep_conv_3x3', 3), ('sep_conv_5x5', 3), ('sep_conv_3x3', 4), ('sep_conv_3x3', 3)], reduce_concat=[2, 3, 4, 5]), 12238.230642330227, 20, 1348, 1302]

I am curious about the specific argument settings used in Appendix F experiments! Also, could you provide information on the swap scores for the architecture results in Figures 18, 19, 20, and 21?

Additionally, I am curious about whether there should be additional constraints in the mutation part of evolutionary search that are not present in the code.

Thank you.

**Comment by pym1024** [comment]
> Hello,
> 
> I ran the previous version of the code that contains `search.py`.
> 
> The code has the following default settings:
> 
> ```
> args = Namespace(cycles=50, data_path='datasets', dataset_name='cifar10', device='cuda', history_path='histories', init_channels=3, input_batch=16, input_dim=32, layers=1, log_path='logs', mutation_times=68, num_classes=10, population_size=128, repeats=32, sample_size=64, search_space='DARTS', seed=0)
> ```
> 
> > args = Namespace(cycles=50, data_path='datasets', dataset_name='cifar10', device='cuda', history_path='histories', init_channels=3, input_batch=16, input_dim=32, layers=1, log_path='logs', mutation_times=68, num_classes=10, population_size=128, repeats=32, sample_size=64, search_space='DARTS', seed=0)
> 
> ```
> # DARTS search space
> OPERATIONS = ['input', 'max_pool_3x3', 'avg_pool_3x3', 'skip_connect', 'sep_conv_3x3', 'sep_conv_5x5', 'dil_conv_3x3', 'dil_conv_5x5', 'output']
> ```
> 
> > OPERATIONS = ['input', 'max_pool_3x3', 'avg_pool_3x3', 'skip_connect', 'sep_conv_3x3', 'sep_conv_5x5', 'dil_conv_3x3', 'dil_conv_5x5', 'output']
> 
> When running the code with default settings, as the evolution progresses, it seems that only architectures composed solely of 'sep_conv_3x3' and 'sep_conv_5x5' operations are considered for computation.
> 
> > INFO  Best architecture: [Genotype(normal=[('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 2), ('sep_conv_3x3', 2), ('sep_conv_3x3', 3), ('sep_conv_5x5', 3), ('sep_conv_3x3', 4), ('sep_conv_3x3', 3)], normal_concat=[2, 3, 4, 5], reduce=[('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 2), ('sep_conv_3x3', 2), ('sep_conv_3x3', 3), ('sep_conv_5x5', 3), ('sep_conv_3x3', 4), ('sep_conv_3x3', 3)], reduce_concat=[2, 3, 4, 5]), 12238.230642330227, 20, 1348, 1302]
> 
> I am curious about the specific argument settings used in Appendix F experiments! Also, could you provide information on the swap scores for the architecture results in Figures 18, 19, 20, and 21?
> 
> Additionally, I am curious about whether there should be additional constraints in the mutation part of evolutionary search that are not present in the code.
> 
> Thank you.

Hi,

The default setting in the version you're running is automatically set mu and sigma based on maximum and mean values (line 90&91 in search.py), thus it leads to large models which only contain convoutional operations. If you wanna find models with different sizes, like Figures 18-21, you need to manually set the regularisation parameter, e.g., set mu to 0.5 if the model size distribution is 0.1-1.5 etc.
