### ISSUE TITLE
Code for Evolutionary algorithm not available

### ISSUE THREAD

**Issue by rohanasthana** [pym1024/SWAP#2]
Hi,

I could not find the code for NAS experiments on DARTS search space using evolutionary algorithm described in the appendix of the paper. Can you please tell me where can I find it and if there isn't, can you please upload the same? 

Thank you!

**Comment by pym1024** [comment]
Hi there,

We detached the SWAP-score and the search algorithm as, we don't wanna audiences felt the metric is limited to a specific search algorithm or limited to the NAS scenario. If you favour the evolutionary search algorithm, you can refer to the algorithm in [AmoebaNet](https://paperswithcode.com/paper/regularized-evolution-for-image-classifier).

**Comment by rohanasthana** [comment]
Hi,

Thank you for your fast reply. In the appendix of your paper, you have
described some changes you made from the standard evolutionary algorithm
from AmoebaNet. For instance, random crossover selection. It would be
really nice if you can atleast provide the function for the new search
algorithm.

Moreover, how you process the DARTS search space to have matrices for
evolutionary algorithm would also be really helpful. Hence, i suggested to
provide the code for NAS algorithm.

Thank you!

**Comment by pym1024** [comment]
Hi there,

The relevant code can be found in the supplementary materials. 
For the architecture encoding, each cell of the matrix indicates a potential connection between two network nodes. For visual aids, you can refer to the [BONAS](https://arxiv.org/pdf/1911.09336).
